### PR TITLE
NETWORK.ETHTOOL: Skip Get/Set msg level test if kernel symbols missing

### LINKED ISSUE #341: NETWORK.ETHTOOL-GET-SET-MSG-LEVEL Not supported
Setting the MSG level seems to be unsupported by some kernels and the test fails because of it,
Maybe we could skip the test if the action is not supported?

```
Wed Jun 19 05:28:24 2019 : The network interface is eth0
Wed Jun 19 05:28:24 2019 : Try to set tx_done and rx_status flags on eth0
Wed Jun 19 05:28:24 2019 : Cannot get msglvl: Operation not supported
Wed Jun 19 05:28:24 2019 : Setting the driver message type flags from ethtool is not supported on Linux 4.15.0-1047-azure
```

### PR DESCRIPTION
**Pull request by stefanlupsa**
* check for get / set msg level symbols in the lib of the current kernel, if missing skip the test.
* if module is builtin check in /boot/System.map of the current kernel.

Fixes #341 
(Continued #363)

Canonical UbuntuServer 18.04-LTS 18.04.201906040
Kernel module, contains functionality: expected pass
```
[azure] [LISAv2 Test Results Summary]
[azure] Test Run On           : 06/25/2019 16:18:25
[azure] ARM Image Under Test  : Canonical : UbuntuServer : 18.04-LTS : 18.04.201906040
[azure] Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
[azure] Total Time (dd:hh:mm) : 0:0:3
[azure] 
[azure]    ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
[azure] -------------------------------------------------------------------------------------------------------------------------------------------
[azure]     1 NETWORK              ETHTOOL-GET-SET-MSG-LEVEL                                                         PASS                 1.14 
```

Canonical UbuntuServer 16.04-LTS 16.04.201906050
Kernel module, does not contain functionality: expect skipped
```
[azure] [LISAv2 Test Results Summary]
[azure] Test Run On           : 06/25/2019 16:18:16
[azure] ARM Image Under Test  : Canonical : UbuntuServer : 16.04-LTS : 16.04.201906050
[azure] Total Test Cases      : 1 (0 Passed, 0 Failed, 0 Aborted, 1 Skipped)
[azure] Total Time (dd:hh:mm) : 0:0:3
[azure] 
[azure]    ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
[azure] -------------------------------------------------------------------------------------------------------------------------------------------
[azure]     1 NETWORK              ETHTOOL-GET-SET-MSG-LEVEL                                                      SKIPPED                 0.69 
```

RedHat RHEL 7-RAW 7.6.2019062020
Archived kernel module, does not contain functionality: expect skipped
```
[azure] [LISAv2 Test Results Summary]
[azure] Test Run On           : 06/25/2019 16:17:04
[azure] ARM Image Under Test  : RedHat : RHEL : 7-RAW : 7.6.2019062020
[azure] Total Test Cases      : 1 (0 Passed, 0 Failed, 0 Aborted, 1 Skipped)
[azure] Total Time (dd:hh:mm) : 0:0:3
[azure] 
[azure]    ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
[azure] -------------------------------------------------------------------------------------------------------------------------------------------
[azure]     1 NETWORK              ETHTOOL-GET-SET-MSG-LEVEL                                                      SKIPPED                 0.72 
```

SUSE SLES 15 2019.06.17
Kernel builtin, contains functionality, expect pass
```
[azure] [LISAv2 Test Results Summary]
[azure] Test Run On           : 06/25/2019 16:16:10
[azure] ARM Image Under Test  : SUSE : SLES : 15 : 2019.06.17
[azure] Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
[azure] Total Time (dd:hh:mm) : 0:0:5
[azure] 
[azure]    ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
[azure] -------------------------------------------------------------------------------------------------------------------------------------------
[azure]     1 NETWORK              ETHTOOL-GET-SET-MSG-LEVEL                                                         PASS                  0.5 
```

### CODE REVIEW

File: Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh [hunk 1]
```diff
@@ -23,6 +23,36 @@ UtilsInit
...
 #######################################################################
+# Check if feature is supported by the kernel
+if ! which nm; then
+    update_repos
+    install_package binutils
+fi
+
+kernel_version=$(uname -r)
+# if the module is not builtin
+if [ "$(grep -c netvsc < /lib/modules/"$kernel_version"/modules.builtin)" == 0 ]; then
```
Comment (ader1990) [inline Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh]: reuse /lib/modules/ by putting in a variable

File: Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh [hunk 2]
```diff
@@ -23,6 +23,36 @@ UtilsInit
...
+    # if the module is archived as xz, extract it to check symbols
+    if [ "$(echo "$kernel_module" | grep -c ".xz")" -ne 0 ]; then
+        cp "$kernel_module" .
+        xz -d "$(basename "$kernel_module")"
+        kernel_module=$(ls hv_netvsc*)
+    fi
+    msg_level_symbols=$(nm "$kernel_module" | grep msglevel)
+else
+    LogMsg "netvsc module is builtin, looking for msg level symbols in System.map..."
+    msg_level_symbols=$(grep 'netvsc.*msglevel' "/boot/System.map-$(uname -r)")
```
Comment (ader1990) [inline Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh]: uname -r is kernel_version

File: Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh [hunk 3]
```diff
@@ -23,6 +23,36 @@ UtilsInit
...
+fi
+LogMsg "Msg level symbols: $msg_level_symbols"
+if [[ "$msg_level_symbols" != *netvsc_get_msglevel* ]] || [[ "$msg_level_symbols" != *netvsc_set_msglevel* ]]; then
+    UpdateSummary "Getting / Setting the driver message type flags from ethtool is not supported on $kernel_version, skipping test."
```
Comment (ader1990) [inline Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh]: line too long, try to shrink the message to a more concise version

**Review by ader1990 — CHANGES_REQUESTED** [review]

File: Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh [hunk 4]
```diff
@@ -23,6 +23,37 @@ UtilsInit
 #######################################################################
 # Main script body
 #######################################################################
+# Check if feature is supported by the kernel
+if ! which nm; then
```
Comment (chvalean) [inline Testscripts/Linux/ETHTOOL-MSG-LEVEL.sh]: move the check/install for nm in the if section below, only if netvsc is present as a module.

**Review by ader1990 — APPROVED** [review]
