### PR TITLE
Fix KDUMP + NVME test issues against Ubuntu 14.04

### LINKED ISSUE #394: Need to revise NVMe functions
Target test: NVME-DISK-VALIDATION
Issue: no need install gcc-c++ kernel-devel, lack of make package in function install_nvme_cli

Target test: NVME-FSTRIM
No need install gcc-c++ kernel-devel, lack of make package in function install_nvme_cli, lack of package xfsprogs for mount xfs system

Target test: NVME-BLKDISCARD
no need install gcc-c++ kernel-devel, lack of make package in function install_nvme_cli, lack of xfsprogs in Format_Mount_NVME

Verify fixes in Trusty, Disco and Bionic of Cannonical with default/linuxnext kernel.

### PR DESCRIPTION
**Pull request by LiliDeng**
Fix #394  #391 
```
[LISAv2 Test Results Summary]
Test Run On           : 07/04/2019 09:03:43
VHD Under Test        : EOSG-AUTOBUILT-canonical-u4.15.0-1050.55_14.04.1-6_29.vhd
Total Test Cases      : 3 (3 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:20

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 NVME                 NVME-DISK-VALIDATION                                                              PASS                 2.71 
    2 NVME                 NVME-FSTRIM                                                                       PASS                 6.98 
    3 NVME                 NVME-BLKDISCARD                                                                   PASS                 3.69 

[LISAv2 Test Results Summary]
Test Run On           : 07/04/2019 07:58:22
VHD Under Test        : EOSG-AUTOBUILT-canonical-u4.15.0-1050.55_14.04.1-6_29.vhd
Test Area             : KDUMP
Total Test Cases      : 5 (4 Passed, 1 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:1:50

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SINGLE-CORE                                                           PASS                 5.99 
    2 KDUMP                KDUMP-CRASH-SMP                                                                   PASS                19.62 
    3 KDUMP                KDUMP-CRASH-AUTO-SIZE                                                             PASS                15.87 
    4 KDUMP                KDUMP-CRASH-DIFFERENT-VCPU                                                        PASS                19.81 
    5 KDUMP                KDUMP-CRASH-16-CORES                                                              PASS                5.85  
```

### CODE REVIEW

File: Testscripts/Linux/nvme_blkdiscard.sh [hunk 1]
```diff
@@ -46,6 +47,24 @@ Run_Blkdiscard() {
             LogMsg "Unmounted ${namespace}"
         fi
         #Run blkdiscard on partition
+        which blkdiscard
```
Comment (chvalean) [inline Testscripts/Linux/nvme_blkdiscard.sh]: this will install util-linux from sources if not found already install.
It produces too much overhead, and if you look here that package updates *a lot* of binaries. We don't want to alter the guest distro that much.
https://packages.ubuntu.com/bionic/amd64/util-linux/filelist

I would suggest to just skip this test instead, based on my other PR.

If @juhlee-microsoft still wants to go with this implementation, it needs to be changed to:
1. use install_package util-linux
2. if that fails (package not found or blkdiscard binary not present after install), then go with this manual install.
3. still have a check at the end of this new code to confirm that blkdiscard is present/was installed on the system.

**Review by chvalean — CHANGES_REQUESTED** [review]

File: Testscripts/Linux/KDUMP-Config.sh [hunk 2]
```diff
@@ -6,7 +6,10 @@ kdump_conf=/etc/kdump.conf
 dump_path=/var/crash
 kdump_sysconfig=/etc/sysconfig/kdump
 boot_filepath=""
-
+#Existed bug for kexec-tools https://bugs.launchpad.net/ubuntu/+source/kexec-tools/+bug/1713940
+target_version=2.0.15
+kexec_source_tar="kexec-tools_2.0.15.orig.tar.gz"
```
Comment (chvalean) [inline Testscripts/Linux/KDUMP-Config.sh]: this is the official kexec repo.
https://git.kernel.org/pub/scm/utils/kernel/kexec/kexec-tools.git/

One other issue here - there is no control on the version - now 2.0.15 is good, but in master it's already at 2.0.19.
Maybe have the kexec-tools version as a replaceable param in the xml?

File: Testscripts/Linux/KDUMP-Config.sh [hunk 3]
```diff
@@ -6,7 +6,8 @@ kdump_conf=/etc/kdump.conf
 dump_path=/var/crash
 kdump_sysconfig=/etc/sysconfig/kdump
 boot_filepath=""
-
+#Existed bug for kexec-tools https://bugs.launchpad.net/ubuntu/+source/kexec-tools/+bug/1713940
+kexec_tarball_url="https://mirrors.edge.kernel.org/pub/linux/utils/kernel/kexec/kexec-tools-2.0.18.tar.gz"
```
Comment (LiliDeng) [inline Testscripts/Linux/KDUMP-Config.sh]: https://mirrors.edge.kernel.org/pub/linux/utils/kernel/kexec/kexec-tools.tar.gz is the latest one, 2.0.19, but it has existed bug

**Comment by juhlee-microsoft** [comment]
Duplication with another PR.

**Comment by LiliDeng** [comment]
My PR contains three fix #391 #392 #394, please let know mine is duplicated with which one.
- Install kexec-tools if current kexec version less than 2.0.15 (For KDUMP)
- Install util-linux new version if current distro is ubuntu 16.04 (For NVME-BLKDISCARD)
- Refine install_nvme_cli (For NVME test areas)

**Comment by LiliDeng** [comment]
@juhlee-microsoft Should I fix #391 and #394 ?

File: Testscripts/Linux/KDUMP-Config.sh [hunk 4]
```diff
@@ -37,6 +37,20 @@ Install_Kexec(){
             if [ $? -ne 0 ]; then
                 UpdateSummary "Warning: Kexec-tools failed to install."
             fi
+            #Existed bug for kexec-tools https://bugs.launchpad.net/ubuntu/+source/kexec-tools/+bug/1713940
+            if [[ ("$DISTRO_NAME" == "ubuntu" && "${DISTRO_VERSION}" == "14.04") || "$DISTRO_NAME" == "debian" ]]; then
```
Comment (chvalean) [inline Testscripts/Linux/KDUMP-Config.sh]: can use instead "$DISTRO" == "ubuntu_14.04"
as introduced here: https://github.com/LIS/LISAv2/pull/405/files

File: Testscripts/Linux/nvme_blkdiscard.sh [hunk 5]
```diff
@@ -46,6 +47,21 @@ Run_Blkdiscard() {
             LogMsg "Unmounted ${namespace}"
         fi
         #Run blkdiscard on partition
+        if [[ "$DISTRO_NAME" == "ubuntu" && "${DISTRO_VERSION}" == "14.04" ]]; then
```
Comment (chvalean) [inline Testscripts/Linux/nvme_blkdiscard.sh]: this is no longer required, we skip this test on 14.04 based on this merged PR:
https://github.com/LIS/LISAv2/pull/405/files

File: XML/Other/ReplaceableTestParameters.xml [hunk 6]
```diff
@@ -530,4 +530,12 @@ Scenario 2 : You need to run all the performance tests quickly.
 		<ReplaceThis>VM_HOT_RESIZE_TEST_MODE</ReplaceThis>
 		<ReplaceWith>economy</ReplaceWith>
 	</Parameter>
+	<Parameter>
+		<ReplaceThis>KEXEC_VERSION</ReplaceThis>
+		<ReplaceWith>2.0.18</ReplaceWith>
+	</Parameter>
+	<Parameter>
+		<ReplaceThis>UTIL_LINUX_VERSION</ReplaceThis>
```
Comment (chvalean) [inline XML/Other/ReplaceableTestParameters.xml]: no longer required

**Review by chvalean — CHANGES_REQUESTED** [review]

**Comment by LiliDeng** [comment]
@chvalean Thanks, doing testing against latest code, will post results once done.

**Review by chvalean — APPROVED** [review]

**Comment by LiliDeng** [comment]
Test results 

```
[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 09:17:42
VHD Under Test        : http://lisawestus2.blob.core.windows.net/vhds/EOSG-AUTOBUILT-canonical-u4.15.0-1050.55_14.04.1-6_29.vhd
Total Test Cases      : 2 (2 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:11

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 NVME                 NVME-FSTRIM                                                                       PASS                 5.69 
    2 NVME                 NVME-DISK-VALIDATION                                                              PASS                 1.37 

[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 09:18:39
VHD Under Test        : http://lisawestus2.blob.core.windows.net/vhds/EOSG-AUTOBUILT-canonical-u4.15.0-1050.55_16.04-6_29.vhd
Total Test Cases      : 2 (2 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:13

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 NVME                 NVME-FSTRIM                                                                       PASS                 6.34 
    2 NVME                 NVME-DISK-VALIDATION                                                              PASS                 2.39 

[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 10:16:34
VHD Under Test        : http://lisawestus2.blob.core.windows.net/vhds/EOSG-AUTOBUILT-u5.0.0-1011.11_19.04-7_1.vhd
Total Test Cases      : 2 (2 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:13

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 NVME                 NVME-FSTRIM                                                                       PASS                 5.99 
    2 NVME                 NVME-DISK-VALIDATION                                                              PASS                 2.15 

[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 10:16:13
VHD Under Test        : http://lisawestus2.blob.core.windows.net/vhds/EOSG-AUTOBUILT-canonical-u4.18.0-1024.25_18.10-6_29.vhd
Total Test Cases      : 2 (2 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:13

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 NVME                 NVME-FSTRIM                                                                       PASS                 6.24 
    2 NVME                 NVME-DISK-VALIDATION                                                              PASS                 2.21 

[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 10:15:55
VHD Under Test        : http://lisawestus2.blob.core.windows.net/vhds/EOSG-AUTOBUILT-canonical-u4.18.0-1024.25_18.04.1-6_29.vhd
Total Test Cases      : 2 (2 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:17

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 NVME                 NVME-FSTRIM                                                                       PASS                 7.22 
    2 NVME                 NVME-DISK-VALIDATION                                                              PASS                 2.77 



[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 09:18:21
VHD Under Test        : http://lisawestus2.blob.core.windows.net/vhds/EOSG-AUTOBUILT-canonical-u4.15.0-1050.55_14.04.1-6_29.vhd
Test Area             : KDUMP
Total Test Cases      : 5 (4 Passed, 0 Failed, 0 Aborted, 1 Skipped)
Total Time (dd:hh:mm) : 0:0:37

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SINGLE-CORE                                                           PASS                 4.35 
    2 KDUMP                KDUMP-CRASH-SMP                                                                   PASS                14.25 
    3 KDUMP                KDUMP-CRASH-AUTO-SIZE                                                          SKIPPED                 1.46 
    4 KDUMP                KDUMP-CRASH-DIFFERENT-VCPU                                                        PASS                 4.33 
    5 KDUMP                KDUMP-CRASH-16-CORES                                                              PASS                 3.95 

[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 09:19:06
VHD Under Test        : http://lisawestus2.blob.core.windows.net/vhds/EOSG-AUTOBUILT-canonical-u4.15.0-1050.55_16.04-6_29.vhd
Test Area             : KDUMP
Total Test Cases      : 5 (4 Passed, 0 Failed, 0 Aborted, 1 Skipped)
Total Time (dd:hh:mm) : 0:0:33

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SINGLE-CORE                                                           PASS                 5.31 
    2 KDUMP                KDUMP-CRASH-SMP                                                                   PASS                  5.6 
    3 KDUMP                KDUMP-CRASH-AUTO-SIZE                                                          SKIPPED                 2.53 
    4 KDUMP                KDUMP-CRASH-DIFFERENT-VCPU                                                        PASS                 5.39 
    5 KDUMP                KDUMP-CRASH-16-CORES                                                              PASS                 5.12 

[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 10:13:55
VHD Under Test        : http://lisawestus2.blob.core.windows.net/vhds/EOSG-AUTOBUILT-canonical-u4.18.0-1024.25_18.04.1-6_29.vhd
Test Area             : KDUMP
Total Test Cases      : 5 (3 Passed, 0 Failed, 1 Aborted, 1 Skipped)
Total Time (dd:hh:mm) : 0:0:35

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SINGLE-CORE                                                           PASS                 6.11 
    2 KDUMP                KDUMP-CRASH-SMP                                                                   PASS                 6.24 
    3 KDUMP                KDUMP-CRASH-AUTO-SIZE                                                          SKIPPED                 2.86 
    4 KDUMP                KDUMP-CRASH-DIFFERENT-VCPU                                                        PASS                 5.85 
    5 KDUMP                KDUMP-CRASH-16-CORES                                                              PASS                  5.8

[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 10:14:51
VHD Under Test        : http://lisawestus2.blob.core.windows.net/vhds/EOSG-AUTOBUILT-canonical-u4.18.0-1024.25_18.10-6_29.vhd
Test Area             : KDUMP
Total Test Cases      : 5 (4 Passed, 0 Failed, 0 Aborted, 1 Skipped)
Total Time (dd:hh:mm) : 0:0:44

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SINGLE-CORE                                                           PASS                 5.39 
    2 KDUMP                KDUMP-CRASH-SMP                                                                   PASS                 15.3 
    3 KDUMP                KDUMP-CRASH-AUTO-SIZE                                                          SKIPPED                 2.41 
    4 KDUMP                KDUMP-CRASH-DIFFERENT-VCPU                                                        PASS                 5.57 
    5 KDUMP                KDUMP-CRASH-16-CORES                                                              PASS                  5.4 


[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 10:43:16
ARM Image Under Test  : Oracle : Oracle-Linux : 7.6 : Latest
Total Test Cases      : 3 (3 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:16

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SMP                                                                   PASS                 3.17 
    2 NVME                 NVME-DISK-VALIDATION                                                              PASS                 0.69 
    3 NVME                 NVME-FSTRIM                                                                       PASS                 5.05 

[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 10:42:54
ARM Image Under Test  : OpenLogic : CentOS : 7.5 : Latest
Total Test Cases      : 3 (3 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:17

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SMP                                                                   PASS                 3.21 
    2 NVME                 NVME-DISK-VALIDATION                                                              PASS                 0.62 
    3 NVME                 NVME-FSTRIM                                                                       PASS                 5.12 

[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 10:42:29
ARM Image Under Test  : RedHat : RHEL : 7.5 : Latest
Total Test Cases      : 3 (3 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:21

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SMP                                                                   PASS                 4.02 
    2 NVME                 NVME-DISK-VALIDATION                                                              PASS                 1.89 
    3 NVME                 NVME-FSTRIM                                                                       PASS                 6.07

[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 10:43:40
ARM Image Under Test  : credativ : Debian : 9-backports : Latest
Total Test Cases      : 3 (3 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:19

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SMP                                                                   PASS                 4.77 
    2 NVME                 NVME-DISK-VALIDATION                                                              PASS                 0.59 
    3 NVME                 NVME-FSTRIM                                                                       PASS                 4.93 



[LISAv2 Test Results Summary]
Test Run On           : 07/09/2019 10:44:10
ARM Image Under Test  : SUSE : SLES : 15 : Latest
Total Test Cases      : 3 (2 Passed, 0 Failed, 1 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:1:34

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SMP                                                                   PASS                 3.57 
    2 NVME                 NVME-DISK-VALIDATION                                                              PASS                 0.51 
```
