### PR TITLE
Handling CUDA driver installation failure due to missing kernel-devel in RH/CentOS

### LINKED ISSUE #513: GPU validation test for CUDA driver is failing in RH73 due to "failure to install pre-requisite package"
There are 2 scenarios which needs to be handled for installation of GPU drivers:
1. In function InstallRequirements (Linux/gpu-driver-install.sh), the **installation status of kernel-header and kernel-devel package is not checked**. Due to the failure to install the devel package, nvidia driver installation will fail because nvidia driver will not be compiled. **Currently _test is failing in the later steps due to the missing -devel package_**. Ideally test should be aborted as required dependencies were not installed.

2. In InstallCUDADrivers function (Linux/gpu-driver-install.sh), the nvidia make log is checked but test will continue even the log file was not created or there is an **error in log**. Ideally test should be failure/aborted, since compilation of nvidia driver is failed.
**Snippet of log (nvidia_dkms_make.log)** > File not found, make.log

### PR DESCRIPTION
**Pull request by johnsongeorge-w**
Fix #513

### CODE REVIEW

**Comment by johnsongeorge-w** [comment]
PR tested in Job(1741)

File: Testscripts/Linux/gpu-driver-install.sh [hunk 1]
```diff
@@ -45,6 +45,15 @@ function InstallRequirements() {
             yum -y install kernel-devel-"$(uname -r)" kernel-headers-"$(uname -r)"
         fi
 
+        # Kernel devel package is mandatory for nvdia cuda driver installation.
+        # Failure to install kernel devel should be treated as test aborted not failed.
+        rpm -q --quiet kernel-devel-$(uname -r)
+        if [ $? -ne 0 ]; then
+                LogErr "Failed to install the RH/CentOS kernel-devel package"
```
Comment (LiliDeng) [inline Testscripts/Linux/gpu-driver-install.sh]: Please use consistent indent.

Comment (LiliDeng) [reply Testscripts/Linux/gpu-driver-install.sh]: https://github.com/LIS/LISAv2/pull/538/files#diff-2d71ede9ea2f6b893697e866f101e841R45c install kernel-devel fail, because current corresponding kernel devel not exist in repo?

Comment (johnsongeorge-w) [reply Testscripts/Linux/gpu-driver-install.sh]: > Please use consistent indent.
Fixed.

> https://github.com/LIS/LISAv2/pull/538/files#diff-2d71ede9ea2f6b893697e866f101e841R45c install kernel-devel fail, because current corresponding kernel devel not exist in repo?
Yes.

**Review by LiliDeng — APPROVED** [review]
Please run cuda and grid in positive and negative situation, thanks.

**Review by prashantmhetar — APPROVED** [review]

**Review by iamshital — APPROVED** [review]

**Comment by johnsongeorge-w** [comment]
> Please run cuda and grid in positive and negative situation, thanks.
Tested. Job: 1747. Results are good.
