### PR TITLE
Fix test issues against CentOS 8.0 and Redhat 8.0

### LINKED ISSUE #620: CentOS8 has new changes
1. python is no longer default, so it had to instaill python2 first. And create a soft link in /usr/bin/python.
2. Need to make sure how to do with kdump-tools and makedumpfile dependency installation. They are not in the official repo site.
3. c.	CENTOS_TEST_REPOSITORIES_AVAILABLE & CENTOS_TEST_GRUB_VERIFICATION_SUCCESS are missing.  The meta data shows below only.

_Last metadata expiration check: 0:00:23 ago on Fri 01 Nov 2019 11:19:26 PM UTC.
repo id           repo name                       status
AppStream         CentOS-8 - AppStream            5,532
BaseOS            CentOS-8 - Base                 2,847_

### PR DESCRIPTION
**Pull request by LiliDeng**
Fix #620 
OpenLogic CentOS 8.0 8.0.20191030
For DPDK, if use default version 18.11 will hit build error, this build issue got fixed in version DPDK_SOURCE_URL=https://github.com/DPDK/dpdk/archive/v19.11-rc1.tar.gz

```
[LISAv2 Test Results Summary]
Test Run On           : 11/02/2019 14:05:30
ARM Image Under Test  : OpenLogic : CentOS : 8.0 : 8.0.20191030
Initial Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.11.2.el8_0.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:2

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 LSVMBUS                                                                           PASS                 0.76 


[LISAv2 Test Results Summary]
Test Run On           : 11/02/2019 15:44:48
ARM Image Under Test  : OpenLogic : CentOS : 8.0 : 8.0.20191030
Initial Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.11.2.el8_0.x86_64
Total Test Cases      : 3 (3 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:7

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 CORE                 TIME-CLOCKSOURCE                                                                  PASS                 0.68 
    2 CORE                 TIME-CLOCKEVENT-UP                                                                PASS                 0.54 
    3 CORE                 TIME-CLOCKEVENT-SMP                                                               PASS                 0.43 

[LISAv2 Test Results Summary]
Test Run On           : 11/04/2019 06:25:32
ARM Image Under Test  : OpenLogic : CentOS : 8.0 : 8.0.20191030
Initial Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.11.2.el8_0.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:19

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC                                               PASS                15.41 
dpdk_version test_mode phase   fwdrx_pps_avg fwdtx_pps_avg
------------ --------- -----   ------------- -------------
19.11.0-rc1  txonly    after   5688134       5688135      
19.11.0-rc1  txonly    before  5581744       5581744      
19.11.0-rc1  txonly    during  6380          6380         
19.11.0-rc1  txonly    overall 2327500       2327500 

[LISAv2 Test Results Summary]
Test Run On           : 11/04/2019 06:53:23
ARM Image Under Test  : OpenLogic : CentOS : 8.0 : 8.0.20191030
Initial Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.11.2.el8_0.x86_64
Total Test Cases      : 2 (2 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:14

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-COMPLIANCE                                                            PASS                 6.21 
    2 DPDK                 VERIFY-DPDK-RING-LATENCY                                                          PASS                 4.93 

[LISAv2 Test Results Summary]
Test Run On           : 11/04/2019 06:59:05
ARM Image Under Test  : OpenLogic : CentOS : 8.0 : 8.0.20191030
Test Area             : KDUMP
Initial Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.11.2.el8_0.x86_64
Total Test Cases      : 5 (4 Passed, 0 Failed, 0 Aborted, 1 Skipped)
Total Time (dd:hh:mm) : 0:0:14

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 KDUMP                KDUMP-CRASH-SINGLE-CORE                                                           PASS                 2.93 
    2 KDUMP                KDUMP-CRASH-SMP                                                                   PASS                 2.89 
    3 KDUMP                KDUMP-CRASH-AUTO-SIZE                                                          SKIPPED                 0.44 
    4 KDUMP                KDUMP-CRASH-DIFFERENT-VCPU                                                        PASS                 2.85 
    5 KDUMP                KDUMP-CRASH-16-CORES                                                              PASS                 2.93 

[LISAv2 Test Results Summary]
Test Run On           : 11/04/2019 07:41:02
ARM Image Under Test  : OpenLogic : CentOS : 8.0 : 8.0.20191030
Initial Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.11.2.el8_0.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:48

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 NVME                 NVME-FILE-SYSTEM-VERIFICATION-GENERIC                                             PASS                45.68

[LISAv2 Test Results Summary]
Test Run On           : 11/04/2019 12:37:59
ARM Image Under Test  : OpenLogic : CentOS : 8.0 : 8.0.20191030
Initial Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.11.2.el8_0.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:7

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 NESTED               NESTED-KVM-BASIC-VERIFICATION                                                     PASS                 4.82  
```

### CODE REVIEW

**Comment by LiliDeng** [comment]
RedHat RHEL 8 8.0.2019101800

```
[LISAv2 Test Results Summary]
Test Run On           : 11/04/2019 12:04:10
ARM Image Under Test  : RedHat : RHEL : 8 : 8.0.2019101800
Initial Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.11.2.el8_0.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:21

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-FAILSAFE-DURING-TRAFFIC                                               PASS                16.52 
dpdk_version test_mode phase   fwdrx_pps_avg fwdtx_pps_avg
------------ --------- -----   ------------- -------------
19.11.0-rc1  txonly    after   5830380       5830380      
19.11.0-rc1  txonly    before  5736525       5736525      
19.11.0-rc1  txonly    during  11700         11700        
19.11.0-rc1  txonly    overall 2326796       2326796 

[LISAv2 Test Results Summary]
Test Run On           : 11/04/2019 13:11:25
ARM Image Under Test  : RedHat : RHEL : 8 : 8.0.2019101800
Initial Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.11.2.el8_0.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:10

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-RING-LATENCY                                                          PASS                  7.4 


[LISAv2 Test Results Summary]
Test Run On           : 11/04/2019 13:24:29
ARM Image Under Test  : RedHat : RHEL : 8 : 8.0.2019101800
Initial Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.11.2.el8_0.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:9

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 DPDK                 VERIFY-DPDK-COMPLIANCE                                                            PASS                 7.14 

[LISAv2 Test Results Summary]
Test Run On           : 11/04/2019 13:39:14
ARM Image Under Test  : RedHat : RHEL : 8 : 8.0.2019101800
Initial Kernel Version: 4.18.0-80.11.2.el8_0.x86_64
Final Kernel Version  : 4.18.0-80.11.2.el8_0.x86_64
Total Test Cases      : 1 (1 Passed, 0 Failed, 0 Aborted, 0 Skipped)
Total Time (dd:hh:mm) : 0:0:7

   ID TestArea             TestCaseName                                                                TestResult TestDuration(in minutes) 
-------------------------------------------------------------------------------------------------------------------------------------------
    1 NESTED               NESTED-KVM-BASIC-VERIFICATION                                                     PASS                 5.32 
```

File: Testscripts/Linux/gpu-driver-install.sh [hunk 1]
```diff
@@ -208,7 +208,7 @@ if [ $? -ne 0 ]; then
     exit 0
 fi
 
-if [[ $DISTRO == "redhat_8" ]]; then
+if [ -f /usr/libexec/platform-python ]; then
```
Comment (juhlee-microsoft) [inline Testscripts/Linux/gpu-driver-install.sh:211]: This points to python3. I thought we uses python2. Please clarify.

**Review by juhlee-microsoft — CHANGES_REQUESTED** [review]

File: Testscripts/Linux/gpu-driver-install.sh (hunk 1 above)
Comment (LiliDeng) [reply Testscripts/Linux/gpu-driver-install.sh:211]: both versions work

**Review by juhlee-microsoft — APPROVED** [review]
